version: "3.9"
services:
  goss_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1211:1211"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
  goss_redis:
    image: redis
